# Generated by Django 5.2.7 on 2025-10-20 09:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contribution_type', models.CharField(choices=[('one_time', 'One-time Payment'), ('monthly', 'Monthly Contribution'), ('installment', 'Installment Plan')], default='one_time', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount for one-time or monthly payments', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for installment plans', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Congregant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Madzibaba', 'Madzibaba'), ('Madzimai', 'Madzimai')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('installment_count', models.PositiveIntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(limit_choices_to={'contribution_type': 'installment'}, on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='genesis.activity')),
                ('congregant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='genesis.congregant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('activity', 'congregant')},
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('installment', 'Installment'), ('extra', 'Extra Payment')], default='deposit', max_length=20, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_status', models.CharField(blank=True, max_length=50)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('installment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='genesis.installmentplan')),
            ],
            options={
                'ordering': ['payment_date', 'recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('one_time', 'One-time Payment'), ('monthly', 'Monthly Payment')], default='one_time', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_month', models.DateField(blank=True, help_text='For monthly payments, specify the month this payment is for', null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check')], default='cash', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_status', models.CharField(blank=True, max_length=50)),
                ('activity', models.ForeignKey(limit_choices_to={'contribution_type__in': ['one_time', 'monthly']}, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='genesis.activity')),
                ('congregant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='genesis.congregant')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-recorded_at'],
                'unique_together': {('congregant', 'activity', 'payment_month')},
            },
        ),
    ]
