# Generated by Django 5.2.7 on 2025-10-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='installmentplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='congregant',
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='contribution',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='genesis.activity'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('deposit', 'Deposit'), ('installment', 'Installment'), ('monthly', 'Monthly')], default='full', max_length=20),
        ),
        migrations.DeleteModel(
            name='InstallmentPayment',
        ),
        migrations.DeleteModel(
            name='InstallmentPlan',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='payment_month',
        ),
    ]
